[package]
name = "solana-vanity-seed"
version = "0.1.0"
edition = "2021"

[dependencies]
bip39 = "2.1.0"
solana-sdk = "1.18.0"
clap = { version = "4.5.0", features = ["derive"] }
rayon = "1.10.0"
bs58 = "0.5.0"
rand = "0.8"
num_cpus = "1.13"
